# Generated by Django 4.1.3 on 2022-12-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalcategory_board'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='current_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Создание не запрашивалось'), (1, 'Запрос категории'), (3, 'Запрос заголовка')], default=0, verbose_name='Статус'),
        ),
    ]
