# Generated by Django 4.1.3 on 2022-12-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_current_category_tguser_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Создание не запрашивалось'), (1, 'Запрос категории'), (2, 'Запрос заголовка')], default=0, verbose_name='Статус'),
        ),
    ]
